import Order from "../models/order.model.js"
import OrderStatus from "../models/orderStatus.model.js"

let dummyOrder = [
    {
        school_id: "SCH-201",
        trustee_id: "TRUST-201",
        student_info: { name: "Aarav Sharma", id: "STU-201", email: "aarav.sharma@example.com" },
        gateway_name: "PhonePe",
    },
    {
        school_id: "SCH-202",
        trustee_id: "TRUST-202",
        student_info: { name: "Isha Mehta", id: "STU-202", email: "isha.mehta@example.com" },
        gateway_name: "Razorpay",
    },
    {
        school_id: "SCH-203",
        trustee_id: "TRUST-203",
        student_info: { name: "Rohit Verma", id: "STU-203", email: "rohit.verma@example.com" },
        gateway_name: "Paytm",
    },
    {
        school_id: "SCH-204",
        trustee_id: "TRUST-204",
        student_info: { name: "Kavya Nair", id: "STU-204", email: "kavya.nair@example.com" },
        gateway_name: "CashFree",
    },
    {
        school_id: "SCH-205",
        trustee_id: "TRUST-205",
        student_info: { name: "Sahil Kapoor", id: "STU-205", email: "sahil.kapoor@example.com" },
        gateway_name: "PhonePe",
    },
    {
        school_id: "SCH-206",
        trustee_id: "TRUST-206",
        student_info: { name: "Simran Bhatia", id: "STU-206", email: "simran.bhatia@example.com" },
        gateway_name: "Razorpay",
    },
    {
        school_id: "SCH-207",
        trustee_id: "TRUST-207",
        student_info: { name: "Vikram Joshi", id: "STU-207", email: "vikram.joshi@example.com" },
        gateway_name: "Paytm",
    },
    {
        school_id: "SCH-208",
        trustee_id: "TRUST-208",
        student_info: { name: "Ananya Rao", id: "STU-208", email: "ananya.rao@example.com" },
        gateway_name: "CashFree",
    },
    {
        school_id: "SCH-209",
        trustee_id: "TRUST-209",
        student_info: { name: "Manav Gupta", id: "STU-209", email: "manav.gupta@example.com" },
        gateway_name: "PhonePe",
    },
    {
        school_id: "SCH-210",
        trustee_id: "TRUST-210",
        student_info: { name: "Priya Sethi", id: "STU-210", email: "priya.sethi@example.com" },
        gateway_name: "Razorpay",
    },
    {
        school_id: "SCH-211",
        trustee_id: "TRUST-211",
        student_info: { name: "Krishna Malhotra", id: "STU-211", email: "krishna.malhotra@example.com" },
        gateway_name: "Paytm",
    },
    {
        school_id: "SCH-212",
        trustee_id: "TRUST-212",
        student_info: { name: "Nisha Jain", id: "STU-212", email: "nisha.jain@example.com" },
        gateway_name: "CashFree",
    },
    {
        school_id: "SCH-213",
        trustee_id: "TRUST-213",
        student_info: { name: "Yash Khanna", id: "STU-213", email: "yash.khanna@example.com" },
        gateway_name: "PhonePe",
    },
    {
        school_id: "SCH-214",
        trustee_id: "TRUST-214",
        student_info: { name: "Pooja Ahuja", id: "STU-214", email: "pooja.ahuja@example.com" },
        gateway_name: "Razorpay",
    },
    {
        school_id: "SCH-215",
        trustee_id: "TRUST-215",
        student_info: { name: "Arjun Desai", id: "STU-215", email: "arjun.desai@example.com" },
        gateway_name: "Paytm",
    },
    {
        school_id: "SCH-216",
        trustee_id: "TRUST-216",
        student_info: { name: "Meera Pillai", id: "STU-216", email: "meera.pillai@example.com" },
        gateway_name: "CashFree",
    },
    {
        school_id: "SCH-217",
        trustee_id: "TRUST-217",
        student_info: { name: "Aditya Reddy", id: "STU-217", email: "aditya.reddy@example.com" },
        gateway_name: "PhonePe",
    },
    {
        school_id: "SCH-218",
        trustee_id: "TRUST-218",
        student_info: { name: "Tanya Kaur", id: "STU-218", email: "tanya.kaur@example.com" },
        gateway_name: "Razorpay",
    },
    {
        school_id: "SCH-219",
        trustee_id: "TRUST-219",
        student_info: { name: "Kabir Iyer", id: "STU-219", email: "kabir.iyer@example.com" },
        gateway_name: "Paytm",
    },
    {
        school_id: "SCH-220",
        trustee_id: "TRUST-220",
        student_info: { name: "Rhea D’Souza", id: "STU-220", email: "rhea.dsouza@example.com" },
        gateway_name: "CashFree",
    },
];


export async function insertOrders() {
    await Order.insertMany(dummyOrder)
    console.log("Order Model has seeded succesfully")
}

// let dummyOrderStatus = [
//     {
//         "order_amount": 5000,
//         "transaction_amount": 5000,
//         "payment_mode": "upi",
//         "payment_details": "aarav@ybl",
//         "bank_reference": "YESBNK101",
//         "payment_message": "Payment successful",
//         "status": "success",
//         "error_message": "NA",
//         "payment_time": "2025-09-10T08:14:21.945Z"
//     },
//     {
//         "order_amount": 4500,
//         "transaction_amount": 4500,
//         "payment_mode": "netbanking",
//         "payment_details": "ICICI",
//         "bank_reference": "ICICIBNK22",
//         "payment_message": "Payment pending",
//         "status": "pending",
//         "error_message": "NA",
//         "payment_time": "2025-09-10T09:10:00.000Z"
//     },
//     {
//         "order_amount": 3000,
//         "transaction_amount": 3000,
//         "payment_mode": "card",
//         "payment_details": "HDFC VISA",
//         "bank_reference": "HDFCBNK88",
//         "payment_message": "Payment failed",
//         "status": "failed",
//         "error_message": "Insufficient funds",
//         "payment_time": "2025-09-10T11:30:00.000Z"
//     },
//     {
//         "order_amount": 2500,
//         "transaction_amount": 2500,
//         "payment_mode": "upi",
//         "payment_details": "priya@oksbi",
//         "bank_reference": "SBIUPI44",
//         "payment_message": "Payment successful",
//         "status": "success",
//         "error_message": "NA",
//         "payment_time": "2025-09-10T14:00:00.000Z"
//     },
//     {
//         "order_amount": 5500,
//         "transaction_amount": 5500,
//         "payment_mode": "upi",
//         "payment_details": "aditya@ybl",
//         "bank_reference": "YESBNK33",
//         "payment_message": "Payment successful",
//         "status": "success",
//         "error_message": "NA",
//         "payment_time": "2025-09-10T16:45:00.000Z"
//     },
//     {
//         "order_amount": 4700,
//         "transaction_amount": 4700,
//         "payment_mode": "upi",
//         "payment_details": "simran@oksbi",
//         "bank_reference": "SBIUPI90",
//         "payment_message": "Payment pending",
//         "status": "pending",
//         "error_message": "NA",
//         "payment_time": "2025-09-10T17:30:00.000Z"
//     },
//     {
//         "order_amount": 2800,
//         "transaction_amount": 2800,
//         "payment_mode": "card",
//         "payment_details": "Mastercard",
//         "bank_reference": "HDFCBNK92",
//         "payment_message": "Payment failed",
//         "status": "failed",
//         "error_message": "Payment gateway timeout",
//         "payment_time": "2025-09-10T18:00:00.000Z"
//     },
//     {
//         "order_amount": 3200,
//         "transaction_amount": 3200,
//         "payment_mode": "upi",
//         "payment_details": "tanya@ybl",
//         "bank_reference": "YESBNK77",
//         "payment_message": "Payment successful",
//         "status": "success",
//         "error_message": "NA",
//         "payment_time": "2025-09-10T19:30:00.000Z"
//     },
//     {
//         "order_amount": 5100,
//         "transaction_amount": 5100,
//         "payment_mode": "netbanking",
//         "payment_details": "AxisBank",
//         "bank_reference": "AXISBNK55",
//         "payment_message": "Payment successful",
//         "status": "success",
//         "error_message": "NA",
//         "payment_time": "2025-09-10T20:15:00.000Z"
//     },
//     {
//         "order_amount": 4000,
//         "transaction_amount": 4000,
//         "payment_mode": "upi",
//         "payment_details": "neha@okicici",
//         "bank_reference": "ICICIBNK40",
//         "payment_message": "Payment pending",
//         "status": "pending",
//         "error_message": "NA",
//         "payment_time": "2025-09-10T21:45:00.000Z"
//     }
// ]

const orderStatusData = [
  {
    collect_id: "ORDER_ID_1",
    order_amount: 2100,
    transaction_amount: 2100,
    payment_mode: "UPI",
    payment_details: "aarav@ybl",
    bank_reference: "BANKREF201",
    payment_message: "Payment successful",
    status: "success",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_2",
    order_amount: 2200,
    transaction_amount: 2200,
    payment_mode: "NetBanking",
    payment_details: "isha@ybl",
    bank_reference: "BANKREF202",
    payment_message: "Processing",
    status: "pending",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_3",
    order_amount: 2300,
    transaction_amount: 2300,
    payment_mode: "Card",
    payment_details: "rohit@ybl",
    bank_reference: "BANKREF203",
    payment_message: "Payment failed",
    status: "failed",
    error_message: "Transaction declined by bank",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_4",
    order_amount: 2400,
    transaction_amount: 2400,
    payment_mode: "UPI",
    payment_details: "kavya@ybl",
    bank_reference: "BANKREF204",
    payment_message: "Payment successful",
    status: "success",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_5",
    order_amount: 2500,
    transaction_amount: 2500,
    payment_mode: "UPI",
    payment_details: "sahil@ybl",
    bank_reference: "BANKREF205",
    payment_message: "Processing",
    status: "pending",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_6",
    order_amount: 2600,
    transaction_amount: 2600,
    payment_mode: "Card",
    payment_details: "simran@ybl",
    bank_reference: "BANKREF206",
    payment_message: "Payment failed",
    status: "failed",
    error_message: "Insufficient balance",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_7",
    order_amount: 2700,
    transaction_amount: 2700,
    payment_mode: "UPI",
    payment_details: "vikram@ybl",
    bank_reference: "BANKREF207",
    payment_message: "Payment successful",
    status: "success",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_8",
    order_amount: 2800,
    transaction_amount: 2800,
    payment_mode: "NetBanking",
    payment_details: "ananya@ybl",
    bank_reference: "BANKREF208",
    payment_message: "Processing",
    status: "pending",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_9",
    order_amount: 2900,
    transaction_amount: 2900,
    payment_mode: "Card",
    payment_details: "manav@ybl",
    bank_reference: "BANKREF209",
    payment_message: "Payment failed",
    status: "failed",
    error_message: "Payment gateway timeout",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_10",
    order_amount: 3000,
    transaction_amount: 3000,
    payment_mode: "UPI",
    payment_details: "priya@ybl",
    bank_reference: "BANKREF210",
    payment_message: "Payment successful",
    status: "success",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_11",
    order_amount: 3100,
    transaction_amount: 3100,
    payment_mode: "NetBanking",
    payment_details: "krishna@ybl",
    bank_reference: "BANKREF211",
    payment_message: "Processing",
    status: "pending",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_12",
    order_amount: 3200,
    transaction_amount: 3200,
    payment_mode: "Card",
    payment_details: "nisha@ybl",
    bank_reference: "BANKREF212",
    payment_message: "Payment failed",
    status: "failed",
    error_message: "Card expired",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_13",
    order_amount: 3300,
    transaction_amount: 3300,
    payment_mode: "UPI",
    payment_details: "yash@ybl",
    bank_reference: "BANKREF213",
    payment_message: "Payment successful",
    status: "success",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_14",
    order_amount: 3400,
    transaction_amount: 3400,
    payment_mode: "NetBanking",
    payment_details: "pooja@ybl",
    bank_reference: "BANKREF214",
    payment_message: "Processing",
    status: "pending",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_15",
    order_amount: 3500,
    transaction_amount: 3500,
    payment_mode: "Card",
    payment_details: "arjun@ybl",
    bank_reference: "BANKREF215",
    payment_message: "Payment failed",
    status: "failed",
    error_message: "Bank declined payment",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_16",
    order_amount: 3600,
    transaction_amount: 3600,
    payment_mode: "UPI",
    payment_details: "meera@ybl",
    bank_reference: "BANKREF216",
    payment_message: "Payment successful",
    status: "success",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_17",
    order_amount: 3700,
    transaction_amount: 3700,
    payment_mode: "NetBanking",
    payment_details: "aditya@ybl",
    bank_reference: "BANKREF217",
    payment_message: "Processing",
    status: "pending",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_18",
    order_amount: 3800,
    transaction_amount: 3800,
    payment_mode: "Card",
    payment_details: "tanya@ybl",
    bank_reference: "BANKREF218",
    payment_message: "Payment failed",
    status: "failed",
    error_message: "Insufficient funds",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_19",
    order_amount: 3900,
    transaction_amount: 3900,
    payment_mode: "UPI",
    payment_details: "kabir@ybl",
    bank_reference: "BANKREF219",
    payment_message: "Payment successful",
    status: "success",
    error_message: "NA",
    payment_time: new Date(),
  },
  {
    collect_id: "ORDER_ID_20",
    order_amount: 4000,
    transaction_amount: 4000,
    payment_mode: "NetBanking",
    payment_details: "rhea@ybl",
    bank_reference: "BANKREF220",
    payment_message: "Processing",
    status: "pending",
    error_message: "NA",
    payment_time: new Date(),
  },
];


export async function insertOrderStatuses() {
    const orders = await Order.find()
    let dummyOrderStatus = orders.map((order, index) => {
        
        return {
            ...orderStatusData[index],
            collect_id: order._id
        }
    })

    dummyOrderStatus = dummyOrderStatus.filter(orderstatus=>orderstatus.hasOwnProperty('order_amount') )
    // console.log(dummyOrderStatus)
    await OrderStatus.insertMany(dummyOrderStatus)
}